"""added stock column

Revision ID: 7f2a4019b8a2
Revises: bb1cc0bbb50d
Create Date: 2023-03-01 23:10:24.664795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f2a4019b8a2'
down_revision = 'bb1cc0bbb50d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'product_categories', ['id'])
    op.add_column('products', sa.Column('stock', sa.Integer(), server_default='1', nullable=False))
    op.create_unique_constraint(None, 'products', ['code'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_column('products', 'stock')
    op.drop_constraint(None, 'product_categories', type_='unique')
    # ### end Alembic commands ###
